### ISSUE TITLE
Collapsing redundant separators and up-level references

### ISSUE THREAD

**Issue by rchateauneu** [nbeaver/pip_file_lookup#1]
At the moment, the script does not seem to collapse up-level references. For exemple, this file is stored as-is:
'/usr/lib64/python2.7/site-packages/mysqlclient-1.3.12-py2.7.egg-info/../MySQLdb/converters.py'

Therefore this command does not work:
$ python pip_file_lookup.py /usr/lib64/python2.7/site-packages/MySQLdb/converters.py
ERROR:root:could not match path: /usr/lib64/python2.7/site-packages/MySQLdb/converters.py

A suggestion could be to use os.path.normpath(path) which normalizes a pathname by collapsing redundant separators:
            # paths_absolute = [os.path.join(dist.egg_info, p) for p in paths]
            paths_absolute = [ os.path.normpath( os.path.join(dist.egg_info, p) ) for p in paths]

$ python pip_file_lookup.py /usr/lib64/python2.7/site-packages/MySQLdb/converters.py
mysqlclient

Thanks

**Comment by nbeaver** [comment]
Done!

https://github.com/nbeaver/pip_file_lookup/commit/3f1adec130936531500923914b5ba0999ecea006
